### ISSUE TITLE
写频后乱码

### ISSUE THREAD

**Issue by rinyama** [silenty4ng/k5web#13]
![QQ截图20240414014717](https://github.com/silenty4ng/k5web/assets/20681873/955b70c4-0692-4774-9fdb-a0160b062ca4)
![QQ截图20240414014729](https://github.com/silenty4ng/k5web/assets/20681873/55d6fa32-b64f-4dd6-9e68-a315d8bfa744)
![QQ截图20240414014940](https://github.com/silenty4ng/k5web/assets/20681873/0d68794b-74cb-4f7c-b342-870bbc3047fd)
![QQ截图20240414015159](https://github.com/silenty4ng/k5web/assets/20681873/56ddf978-3493-4d2b-820d-6d1e9ff0de32)
读取时没有问题，写频一次后机器出现乱码。重新读取一次后网页也会乱码，使用chirp读取部分信道无法显示

**Comment by silenty4ng** [comment]
简繁转换使用的库文档有误导致，处理中。

**Comment by silenty4ng** [comment]
已修复。
