### ISSUE TITLE
yarn报错

### ISSUE THREAD

**Issue by dan91ng** [silenty4ng/k5web#15]
你好，我使用 yarn 命令安装依赖时出现以下报错，请问如何解决？
error /usr/src/app/node_modules/optipng-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: /usr/src/app/node_modules/optipng-bin
Output:
spawn /usr/src/app/node_modules/optipng-bin/vendor/optipng ENOENT
optipng pre-build test failed
compiling from source
Error: Command failed: /bin/sh -c make install
make: /bin/sh: Operation not permitted
make: *** [Makefile:14: install] Error 127

cd src/optipng && \
make install && \
cd ../..

**Comment by silenty4ng** [comment]
从报错看，你的系统没有 /bin/sh ？

**Comment by dan91ng** [comment]
是在node18的docker中运行的，测试过，有/bin/sh的，很奇怪

**Comment by dan91ng** [comment]
问题解决了，用/bin/sh重新执行就可以了
