### ISSUE TITLE
4Mib扩容版完整备份到51%左右无法继续

### ISSUE THREAD

**Issue by ponyjoy** [silenty4ng/k5web#22]
4Mib扩容版完整备份到51%左右无法继续，浏览器提示 Out of Memory
计算机32GB内存，浏览器Edge　123.0.2420.97

**Comment by silenty4ng** [comment]
泉盛送的绿色版还没到，等到了我试试。

**Comment by ponyjoy** [comment]
更新下，换了CentBrowser百分浏览器， 5.1.1130.123版本（ (Chromium 118.0.5993.159)，绿色扩容版备份正常。应该是浏览器问题。
