### ISSUE TITLE
UV-K6设置数字亚音无法选取254.1以后的数值。

### ISSUE THREAD

**Issue by bfc-lab** [silenty4ng/k5web#30]
bd8fn您好，非常感谢您的辛勤付出。近日改装了一台UV-K6，4Mbits+4732。在设置信道数字亚音时发现，无法选取254.1以后的数值，请您有空的时候帮忙测试一下。感谢。de bg6wuh vy73!
![K6-数字亚音](https://github.com/user-attachments/assets/b5aa44df-5755-4722-9f35-ddce888174af)

**Comment by silenty4ng** [comment]
数字亚音的设置列在后面

**Comment by bfc-lab** [comment]
谢谢，我看错了列。乌龙了，抱歉抱歉。
