### ISSUE TITLE
可以增加NOAA系列卫星吗

### ISSUE THREAD

**Issue by rinyama** [silenty4ng/k5web#7]

**Comment by silenty4ng** [comment]
星历数据来自：amateur

**Comment by silenty4ng** [comment]
当前星历数据来自：https://celestrak.org/NORAD/elements/amateur.txt
当前上下行频率数据来自：https://raw.githubusercontent.com/palewire/ham-satellite-database/main/data/amsat-active-frequencies.json

NOAA 系列卫星相关数据有对应的管理项目的情况下，可以提供支持。

**Comment by rinyama** [comment]
频率是固定的
NOAA-15 | 137.6200
NOAA-18 | 137.9125
NOAA-19 | 137.1000
星历数据这个可以用吗https://github.com/minexixi/AutoTLE

**Comment by silenty4ng** [comment]
固定频率显得太随意了点。
